repositoryUriPrefix: "registry.aquasec.com" # for dockerhub - "docker.io"

dockerSock:
  mount: # put true for mount docker socket.
  path: /var/run/docker.sock # pks - /var/vcap/data/sys/run/docker/docker.sock

serviceAccount: "aqua-sa"
server:
  serviceName: "aqua-console-svc" # example
  port: 8080

image:
  repository: scanner
  tag: "5.3"
  pullPolicy: IfNotPresent

logLevel:


vaultSecret:
  enabled: false   #enable this once you have secrets in vault and annotations are enabled

annotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/agent-inject-status: update
  vault.hashicorp.com/role: "aqua"                            # specify your role used by vault agent auto-auth
  vault.hashicorp.com/agent-inject-secret-aqua-secrets: aqua-v2/data/aqua-secrets  #specify your vault secrets path
  #Add the secrets in Key Value pair as environment variable
  vault.hashicorp.com/agent-inject-template-aqua-secrets: |        
    {{- with secret "aqua-v2/data/aqua-secrets" -}} 
    export AQUA_SCANNER_USERNAME={{ .Data.data.aqua_scanner_user }}
    export AQUA_SCANNER_PASSWORD={{ .Data.data.aqua_scanner_password }}
    {{- end -}}

vaultFilepath:
  /vault/secrets/aqua-secrets      # change the /vault/secrets/<filename> as per the setup

user: 
password: 
replicaCount: 1
livenessProbe: {}
readinessProbe: {}
resources: {}
  # Note: For recommendations please check the official sizing guide.
  # requests:
  #   cpu: 500
  #   memory: 1Gi
  # limits:
  #   cpu: 3000
  #   memory: 5Gi
nodeSelector: {}
tolerations: []
affinity: {}
securityContext: {}
#  runAsUser: 11431
#  runAsGroup: 11433
#  fsGroup: 11433

# extraEnvironmentVars is a list of extra environment variables to set in the scanner deployments.
# https://docs.aquasec.com/docs/scanner-optional-variables
extraEnvironmentVars: {}
  # ENV_NAME: value

# extraSecretEnvironmentVars is a list of extra environment variables to set in the scanner deployments.
# These variables take value from existing Secret objects.
extraSecretEnvironmentVars: []
  # - envName: ENV_NAME
  #   secretName: name
  #   secretKey: key